apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdatasample
  labels:
    app: userdatasample
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: userdatasample
  template:
    metadata:
      labels:
        app: userdatasample
    spec:
      containers:
        - name: userdatasample
          image: gcr.io/innov-htfr-0mhe-1/userdatasample 
          ports:
            - containerPort: 8080
          envFrom: 
          - configMapRef:
              name: my-config-map 
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-config-map
                  key: database_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: my-config-map
                  key: database_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
