apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdatasample
  labels:
    app: userdatasample
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: userdatasample
  template:
    metadata:
      labels:
        app: userdatasample
    spec:
      containers:
        - name: userdatasample
          image: gcr.io/innov-htfr-0mhe-1/userdatasample:v9
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /app/config # Mount path inside the container
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-config-map
                  key: database_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: my-config-map
                  key: database_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            - name: OTHER_CONFIG_KEY  # Define the environment variable name
              valueFrom:
                configMapKeyRef:
                  name: my-config-map
                  key: other_config_key
      volumes:
      - name: config-volume
        configMap:
          name: my-config-map 
